# k8s/person-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
  namespace: person-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: person-service
          image: minhtricao/person-service:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka.person-app.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: person-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: person-service
