server:
  port: 8086
  prefix: /api/v1

spring:
  application:
    name: camunda-service

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    topics:
      person-events:
        name: person.events
        fixed-backoff:
          interval: 0
          max-attempts: 3
      tax-calculation:
        single:
          name: tax.calculation
        retry:
          name: tax.calculation-retry
          header: retry-count
          max-retries: 3
        dlt:
          name: tax.calculation-dlt
        batch:
          name: tax.calculation-batch
        manual:
          name: tax.calculation-manual-consume
          partitions: 3
    groups:
      person-events:
        name: person-group
      tax-calculation:
        single:
          name: tax-single
        batch:
          name: tax-batch
        manual:
          name: tax-manual
          enable-auto-commit-config: false
          auto-offset-reset-config: earliest
          session-timeout-ms-config: 300000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#logging:
#  level:
#    root: ERROR
#    org.springframework.kafka: ERROR
#    org.hibernate.SQL: ERROR

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.hibernate.SQL: DEBUG

camunda:
  client:
    mode: simple
    auth:
      username: demo
      password: demo
    zeebe:
      enabled: true
      base-url: http://zeebe:26500
    operate:
      enabled: true
      base-url: http://operate:8083
    tasklist:
      enabled: true
      base-url: http://tasklist:8082

zeebe:
  client:
    broker:
      gateway-address: zeebe:26500
    security:
      plaintext: true
