apiVersion: v1
kind: Namespace
metadata:
  name: person-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: person-app
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "persondb"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SERVER_PORT: "8080"
  CRON_SERVER_PORT: "8081"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: person-app
type: Opaque
data:
  POSTGRES_USER: cGVyc29uLXVzZXI=  # person-user
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # password123