apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-service
  namespace: person-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-service
  template:
    metadata:
      labels:
        app: cron-service
    spec:
      nodeSelector:
        service-type: batch
      containers:
      - name: cron-service
        image: cron-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SERVER_PORT
          value: "8081"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: cron-service
  namespace: person-app
spec:
  selector:
    app: cron-service
  ports:
  - port: 8081
    targetPort: 8081