# k8s/cron-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-service
  namespace: person-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-service
  template:
    metadata:
      labels:
        app: cron-service
    spec:
      containers:
        - name: cron-service
          image: minhtricao/cron-service:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cron-service
  namespace: person-app
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: cron-service
