FROM eclipse-temurin:21-jre-alpine


# Set the working directory
WORKDIR /app

#Set profile to build for k8s, can override by docker-compose
ENV SPRING_PROFILES_ACTIVE=prod

# Copy the jar from the builder stage
COPY target/person-*.jar app.jar

# Expose the port Spring Boot runs on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java","-jar","app.jar"]