server:
  port: 8081

spring:
  application:
    name: cron-service

fixed-rate:
  consume-tax-calculation: 5000

person-service:
  consume-url: http://localhost:8080/api/v1/tax-calculation/consume-manual