apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
  namespace: person-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      nodeSelector:
        service-type: application
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - person-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: person-service
        image: person-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: person-app
spec:
  selector:
    app: person-service
  ports:
  - port: 8080
    targetPort: 8080