server:
  port: 8081

spring:
  application:
    name: cron-service

logging:
  level:
    root: INFO

fixed-rate:
  consume-tax-calculation: 5000

person-service:
  consume-url: http://person-service:8080/api/v1/tax-calculation/manual